# Data Pre-processing

In [2]:
import sklearn as sk
import pandas as pd

## Import Data

In [3]:
df = pd.read_csv("US_Accidents_March23.csv")
len(df)

7728394

## Basic Data Preprocessing
To simplify your project a bit, use only the data instances that contain at most 1 missing value. According to our counts:
There are 3,554,549 data instances with no missing values:
There are 244,702 data instances with exactly one missing value.
Hence, your dataset for the project should contain 3,554,549 + 244,702 = 3,799,251

In [4]:
df.dropna(thresh=len(df.columns) - 1, inplace=True)
len(df)

3799251

In [5]:
df.drop(columns=['ID', 'Description', 'Country', 'Source', 'Turning_Loop'], inplace = True)
print(df.columns)
basic_df = df.copy(deep=True)

Index(['Severity', 'Start_Time', 'End_Time', 'Start_Lat', 'Start_Lng',
       'End_Lat', 'End_Lng', 'Distance(mi)', 'Street', 'City', 'County',
       'State', 'Zipcode', 'Timezone', 'Airport_Code', 'Weather_Timestamp',
       'Temperature(F)', 'Wind_Chill(F)', 'Humidity(%)', 'Pressure(in)',
       'Visibility(mi)', 'Wind_Direction', 'Wind_Speed(mph)',
       'Precipitation(in)', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Sunrise_Sunset',
       'Civil_Twilight', 'Nautical_Twilight', 'Astronomical_Twilight'],
      dtype='str')

## Advanced Pre-processing
Goals: 
- Encode all features to numeric values
- Use feature selection/elimination to reduce dimensionality for later analysis

In [6]:
advanced_df = df.copy(deep=True)

# Handle datetime -> integer by extracting integer values
advanced_df["Start_Time"] = pd.to_datetime(advanced_df["Start_Time"], format="ISO8601")
advanced_df["End_Time"] = pd.to_datetime(advanced_df["End_Time"], format="ISO8601")

advanced_df["Duration_Minutes"] = (
    advanced_df["End_Time"] - advanced_df["Start_Time"]
).dt.total_seconds() / 60.0
advanced_df["Start_Hour"] = advanced_df["Start_Time"].dt.hour
advanced_df["Start_DayOfWeek"] = advanced_df["Start_Time"].dt.dayofweek  # 0 = Monday, 6 = Sunday
advanced_df["Start_Month"] = advanced_df["Start_Time"].dt.month
advanced_df.drop(columns=["Start_Time", "End_Time"], inplace=True)

In [7]:
# Drop location cols other than lat/long
advanced_df.drop(
    columns=[
        "City", "County", "Zipcode", "Street", "Airport_Code", "State"
    ],
    inplace=True,
)

In [8]:
#Convert sunset measures
sunset_fields = ["Sunrise_Sunset", "Civil_Twilight", "Nautical_Twilight", "Astronomical_Twilight"]
for f in sunset_fields:
    advanced_df[f] = advanced_df[f].map({"Day": 1, "Night": 0}) # day = 1, night = 0

In [9]:
# One-hot encode wind direction and weather condition as dense columns
import numpy as np
from sklearn.preprocessing import OneHotEncoder

weather_columns = ["Wind_Direction", "Weather_Condition"]
encoder = OneHotEncoder(
    handle_unknown="ignore"
)

encoded_array = encoder.fit_transform(advanced_df[weather_columns]).toarray()
encoded_df = pd.DataFrame(
    encoded_array,
    index=advanced_df.index,
    columns=encoder.get_feature_names_out(),
)
advanced_df = advanced_df.drop(columns=weather_columns).join(encoded_df)

In [10]:
#Drop timezone, weather
advanced_df.drop(columns = ["Timezone", "Weather_Timestamp"], inplace = True)

In [11]:
advanced_df.info()

<class 'pandas.DataFrame'>
Index: 3799251 entries, 3402762 to 7728393
Columns: 187 entries, Severity to Weather_Condition_nan
dtypes: bool(12), float64(167), int32(3), int64(5)
memory usage: 5.0 GB

In [12]:
advanced_df.head()

,Severity,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),...,Weather_Condition_Thunder and Hail / Windy,Weather_Condition_Thunder in the Vicinity,Weather_Condition_Thunderstorm,Weather_Condition_Thunderstorms and Rain,Weather_Condition_Tornado,Weather_Condition_Widespread Dust,Weather_Condition_Widespread Dust / Windy,Weather_Condition_Wintry Mix,Weather_Condition_Wintry Mix / Windy,Weather_Condition_nan
3402762,3,40.108910,-83.092860,40.112060,-83.031870,3.230,42.1,36.1,58.0,29.76,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3402767,3,39.172393,-84.492792,39.170476,-84.501798,0.500,37.0,29.8,93.0,29.69,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3402768,2,39.063240,-84.032430,39.067310,-84.058510,1.427,35.6,29.2,100.0,29.66,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3402769,2,39.067080,-84.058550,39.063020,-84.032540,1.423,35.6,29.2,100.0,29.66,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3402771,2,41.375310,-81.820170,41.367860,-81.821740,0.521,33.1,30.0,92.0,29.63,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
basic_df.head()

,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Street,City,...,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
3402762,3,2016-02-08 00:37:08,2016-02-08 06:37:08,40.108910,-83.092860,40.112060,-83.031870,3.230,Outerbelt E,Dublin,...,False,False,False,False,False,False,Night,Night,Night,Night
3402767,3,2016-02-08 07:53:43,2016-02-08 13:53:43,39.172393,-84.492792,39.170476,-84.501798,0.500,I-75 S,Cincinnati,...,False,False,False,False,False,False,Day,Day,Day,Day
3402768,2,2016-02-08 08:16:57,2016-02-08 14:16:57,39.063240,-84.032430,39.067310,-84.058510,1.427,State Route 32,Williamsburg,...,False,False,False,False,False,True,Day,Day,Day,Day
3402769,2,2016-02-08 08:16:57,2016-02-08 14:16:57,39.067080,-84.058550,39.063020,-84.032540,1.423,State Route 32,Batavia,...,False,False,False,False,False,False,Day,Day,Day,Day
3402771,2,2016-02-08 11:51:46,2016-02-08 17:51:46,41.375310,-81.820170,41.367860,-81.821740,0.521,I-71 S,Cleveland,...,False,False,False,False,False,False,Day,Day,Day,Day

# Export

In [14]:
%pip install pyarrow

basic_df.to_parquet(
    "basic_processed_data.parquet",
    engine="pyarrow",
    compression="zstd",
    index=True
)

advanced_df.to_parquet(
    "advanced_processed_data.parquet",
    engine="pyarrow",
    compression="zstd",
    index=True
)

Requirement already satisfied: pyarrow in c:\Users\nottu\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (25.0.1)
Note: you may need to restart the kernel to use updated packages.

# Classification

## Dummy Classifier

In [ ]:
Train = sk.model_selection.train_test_split(basic_df)[0]
print("Training data: ", Train)
imputer = sk.impute.SimpleImputer(strategy='mean')
imputer.fit(Train)

dummy = sk.dummy.DummyClassifier(strategy="most_frequent")
dummy_basic = Train.copy().select_dtypes(include=['number'])
dummy_basic.head()
severity = dummy_basic['Severity'].to_numpy()
dummy.fit(dummy_basic,severity)
dummy.predict(dummy_basic)


basicer = Train.copy().select_dtypes(include=['number'])
sk.metrics.confusion_matrix(basicer, dummy_basic)

print("Majority Class Classifier Score: ", dummy.score(dummy_basic, severity))

X           Severity                     Start_Time  \
4063208         2            2022-09-30 08:28:00
7175015         2            2020-01-15 15:58:00
6447237         2            2021-02-26 18:19:00
4322108         4            2022-08-30 04:25:00
4534682         2            2022-02-01 07:04:41
...           ...                            ...
6920526         2            2020-11-13 16:55:00
3668954         2            2023-02-27 17:39:00
5320429         2  2022-10-04 05:43:00.000000000
5133579         2            2022-08-05 21:26:00
6075566         2            2021-08-24 16:42:39

                              End_Time  Start_Lat   Start_Lng    End_Lat  \
4063208            2022-09-30 08:53:00  38.909502  -77.005988  38.908538
7175015            2020-01-15 16:50:22  34.083533 -117.544627  34.083533
6447237            2021-02-26 20:00:00  36.098379  -78.734039  36.096981
4322108            2022-08-30 06:26:31  38.000564  -79.173560  38.010156
4534682            2022-02-01 09:06:32  41.551162  -73.039438  41.551262
...                                ...        ...         ...        ...
6920526            2020-11-13 18:13:23  34.122129 -117.695857  34.120079
3668954            2023-02-27 19:45:20  34.206562 -118.343313  34.196326
5320429  2022-10-04 08:11:50.000000000  33.916419 -117.287204  33.916855
5133579            2022-08-05 22:41:02  28.005115  -81.779304  28.004952
6075566            2021-08-24 18:55:05  25.686920  -80.416652  25.684322

            End_Lng  Distance(mi)              Street              City  ...  \
4063208  -77.004954         0.087      Florida Ave NE        Washington  ...
7175015 -117.544627         0.000              I-15 N  Rancho Cucamonga  ...
6447237  -78.735831         0.139         Hunters Trl         Creedmoor  ...
4322108  -79.163389         0.864              I-64 E        Greenville  ...
4534682  -73.037288         0.111                I-84         Waterbury  ...
...             ...           ...                 ...               ...  ...
6920526 -117.706897         0.647            CA-210 W         Claremont  ...
3668954 -118.334783         0.859  Golden State Fwy S           Burbank  ...
5320429 -117.287420         0.033     Escondido Fwy N         Riverside  ...
5133579  -81.779519         0.017      Spirit Lake Rd      Winter Haven  ...
6075566  -80.416621         0.180        SW 137th Ave             Miami  ...

        Railway Roundabout Station   Stop Traffic_Calming Traffic_Signal  \
4063208   False      False   False  False           False          False
7175015   False      False   False  False           False          False
6447237   False      False   False  False           False          False
4322108   False      False   False  False           False          False
4534682   False      False   False  False           False          False
...         ...        ...     ...    ...             ...            ...
6920526   False      False   False  False           False          False
3668954   False      False   False  False           False          False
5320429   False      False   False  False           False          False
5133579   False      False   False  False           False           True
6075566   False      False   False  False           False          False

         Sunrise_Sunset  Civil_Twilight  Nautical_Twilight  \
4063208             Day             Day                Day
7175015             Day             Day                Day
6447237           Night             Day                Day
4322108           Night           Night              Night
4534682             Day             Day                Day
...                 ...             ...                ...
6920526           Night             Day                Day
3668954             Day             Day                Day
5320429           Night           Night              Night
5133579           Night           Night              Night
6075566             Day             Day                Day

         Astronomical_Twilight
4063208                    Day
7175015                    Day
6447237                    Day
4322108                  Night
4534682                    Day
...                        ...
6920526                    Day
3668954                    Day
5320429                    Day
5133579                    Day
6075566                    Day

[949813 rows x 41 columns]
Training data:           Severity                     Start_Time  \
6026452         2            2021-06-07 18:37:38
4731372         2            2022-02-22 12:23:00
4239620         2            2022-12-09 15:31:49
7595199         4            2017-12-07 05:09:22
7165341         2            2020-01-08 15:27:00
...           ...                            ...
4149283         2  2022-08-18 13:17:14.000000000
3603342         4            2017-05-09 03:31:57
6494968         2            2021-01-27 03:06:58
6950018         2            2020-06-03 09:47:00
6013587         2            2021-12-28 16:12:00

                              End_Time  Start_Lat   Start_Lng    End_Lat  \
6026452            2021-06-07 20:41:51  25.942301  -80.309583  25.943457
4731372            2022-02-22 14:45:00  30.831639  -82.006105  30.832699
4239620            2022-12-09 16:04:33  35.884688  -78.626983  35.891526
7595199            2017-12-07 11:09:22  39.026680  -76.444100  39.020130
7165341            2020-01-08 16:59:35  34.037581 -118.086252  34.037581
...                                ...        ...         ...        ...
4149283  2022-08-18 14:37:39.000000000  35.748714  -78.844047  35.748693
3603342            2017-05-09 09:31:57  40.080020  -80.902980  40.068210
6494968            2021-01-27 05:04:10  25.714343  -80.416401  25.714364
6950018            2020-06-03 10:39:35  38.538754 -121.370890  38.538754
6013587            2021-12-28 18:25:24  40.425198  -78.088817  40.423419

            End_Lng  Distance(mi)              Street               City  ...  \
6026452  -80.306900         0.185         NW 186th St            Hialeah  ...
4731372  -82.006385         0.075              US-301           Folkston  ...
4239620  -78.627180         0.473   Falls of Neuse Rd            Raleigh  ...
7595199  -76.478860         1.920        Revell Hwy W          Annapolis  ...
7165341 -118.086252         0.000             CA-60 E         Montebello  ...
...             ...           ...                 ...                ...  ...
4149283  -78.843416         0.035         US 64 Hwy W               Apex  ...
3603342  -80.900680         0.825       S Marietta St  Saint Clairsville  ...
6494968  -80.415799         0.038          SW 56th St              Miami  ...
6950018 -121.370890         0.000          Jackson Rd         Sacramento  ...
6013587  -78.091289         0.179      Piney Ridge Rd         Huntingdon  ...

        Railway Roundabout Station   Stop Traffic_Calming Traffic_Signal  \
6026452   False      False   False  False           False          False
4731372   False      False   False  False           False           True
4239620   False      False    True  False           False          False
7595199   False      False   False  False           False          False
7165341   False      False   False  False           False          False
...         ...        ...     ...    ...             ...            ...
4149283   False      False   False  False           False          False
3603342   False      False   False  False           False          False
6494968   False      False   False  False           False          False
6950018   False      False   False  False           False           True
6013587   False      False   False  False           False          False

         Sunrise_Sunset  Civil_Twilight  Nautical_Twilight  \
6026452             Day             Day                Day
4731372             Day             Day                Day
4239620             Day             Day                Day
7595199           Night           Night              Night
7165341             Day             Day                Day
...                 ...             ...                ...
4149283             Day             Day                Day
3603342           Night           Night              Night
6494968           Night           Night              Night
6950018             Day             Day                Day
6013587             Day             Day                Day

         Astronomical_Twilight
6026452                    Day
4731372                    Day
4239620                    Day
7595199                  Night
7165341                    Day
...                        ...
4149283                    Day
3603342                  Night
6494968                  Night
6950018                    Day
6013587                    Day

[2849438 rows x 41 columns]

ValueError: Cannot use mean strategy with non-numeric data:
could not convert string to float: '2021-06-07 18:37:38'

## Decision Tree Classifier

## Random Forest Classifier

## 10 Fold Stratified Cross Verification

## Final Classification Model